### PR TITLE
Update var-sat to not depend on FULL-MAUDE

### PR DESCRIPTION
**Pull request by sskeirik**
All full-maude code has been pulled out into meta-aux; this still needs to be integrated with the existing meta-refactorings. That work can either be done on this pull-request branch or afterwards over time.

At this point, the tests all pass (semantically), but the output is different because of rewrite counts. One interesting point is that this version usually takes more rewrites than the previous version on the example suite. However, the examples here do not have the structure which the embedded optimization pass can use.

In either case, the current version's code is cleaner than previous versions, so in my mind it is still a net win.

### CODE REVIEW

**Comment by sskeirik** [comment]
@ehildenb Since you recently did refactoring work, I think it would be good for you to double check that the same refactoring is applied successfully here.

@nishantjr I know you did some work with var-sat previously on another branch so it would be good if you could look at this branch after the conflicts are worked out.

**Comment by sskeirik** [comment]
@ehildenb I thought this would be really quick to wrap-up, but it's taking more time than I have today. I'll have to finish it up later. In the meantime, do you have any general pointers about what you moved where on the meta-refactoring branch? Thanks.

**Comment by nishantjr** [comment]
This is great! Will look at it in detail on the weekend

**Comment by ehildenb** [comment]
@nishantjr I've already begun breaking it up into smaller changes and making sure each small change passes tests, so probably wait at least until I push up a new version of the branch with everything broken out into smaller changes.

I'm also trying to deduplicate code as I go, but I will miss things inevitably.

**Comment by ehildenb** [comment]
@skeirik2, here is a summary of how files have moved:

-   File `varsat/meta-aux.maude => meta.md/meta-aux.md`
-   File `varsat/prelude-aux.maude => meta.md/prelude-aux.md`
-   File `varsat/sort-ops.maude => meta.md/sort-ops.md`
-   File `varsat/renaming.maude => meta.md/variables.md`

The moves are done by copying the updated file over the original file in the repository, then including the new file in the (now stub) file left in `varsat`. In another PR/cleanup we can remove those stub files too.

The one file I haven't managed to move over is `varsat/foform.maude => meta.md/foform.md`. It causes an infinite loop on `tests/tools/meta/purification.maude` somehow.

**Comment by nishantjr** [comment]
Looks great. I'll pull over e291a0ab1 when I get down to bringing Nelson Oppen in to master

**Review by nishantjr — APPROVED** [review]
Looks good. Apart from a minor commit, the changes we want that were previously on master are already incorporated. There may be more on the nelson-oppen branch that I will bring over.

**Comment by sskeirik** [comment]
@ehildenb Thanks for the summary. I'll look at this when I'm done with my current rltool feature. It's taken a bit longer than I had hoped to finish.

**Review by ehildenb — APPROVED** [review]
Ready to merge this. @nishantjr you mention another commit, but I don't see it anywhere in the history or reflog. Not sure if I force pushed over it, but I'm going to merge this once my local run of tests on every commit passes.

**Pull request merged**
