### PR TITLE
Unified FVP Numbers heirarchy

### PR DESCRIPTION
**Pull request by ehildenb**
This adds a markdown-ized unified FVP numbers heirarchy, some tests of said numbers, as well as migrating over other systems/tools which use numbers to the unified implementation.

### CODE REVIEW

**Comment by sskeirik** [comment]
Thoughts about numbers to ponder:
- the FVP-NAT-SORT module seems to be not very useful/interesting on its own --- I say it can be folded into FVP-NAT-CTOR
- if we have a CTOR module for nats, should we have one for ints, bools also? I feel like it would be better to be consistent in whatever choice we make
- I think saying FVP-NAT-PRED would be more consistent with the FVP-NAT-SORT/CTOR naming convention used earlier, instead of PRED-FVP-NAT
- I am not sure if I like the MULT-LOCALLY-FVP-NAT naming convention, but I think it is important to distinguish the fact that multiplication is actually not FVP --- do you guys have a name you all like more?

**Comment by sskeirik** [comment]
Also, more importantly, I found a build failure.

The build process for 'fvp.md' folder assumes a folder 'fvp' exists. However, that folder is currently empty, so it does not exist in the repo. We need some kind of stub file so that the folder exists or we need the build process to create that folder if it does not exist.

EDIT: I saw that you fixed this in your Makefile edit. Thanks.

**Comment by sskeirik** [comment]
In lines 204-206 of numbers, the operator (-_) is applied to regular nats instead of non-zero nats.

**Comment by sskeirik** [comment]
Line 194: ideally, the disequality predicate over the ints should only define the two missing cases:
- two nznegs
- one nzneg, one nat
in order to generate the minimum number of non-redundant variants.

Lines 237-8: the variant multiplication rules ideally should only cover missing cases, in the same vein as the above comment.

Also, after extraneous int variables, you may be able to remove the int variable decls.

**Comment by ehildenb** [comment]
@skeirik2 I've done the following:

-   Tightened the sorts for `_<=_` on `Int`, which led to less variants and smaller sorts for some other variants. I did not do the same for `_*_` because I was not satisfied with any other formulation of it (besides, for multiplication, we won't be doing variant unification on the distributive law anyway). I figure as we have more in-repo proof that tighter sorts would be beneficial, we can do it then.

-   I've renamed the modules, dropping the `LOCALLY` (maybe the general theory doesn't have FVP, but indeed the presented theory there will always only produce finite variants). I think the way to think of the `variant` attribute is something like "allow symbolic execution using this rule".

-   Updated all the systems/tests to reflect the new naming. Indeed we get fewer rewrites in several cases due to the tighter sorts.

If you have any more things we should add, let me know here. Otherwise I'll wait until end of day for approval, then move forward with merging either way.

I've discussed with @nishantjr and I think I'm going to stop waiting for approvals to merge into this repo. It seems there are not enough developers on this repo to sustain a full "approve every PR before merge" model.

**Comment by sskeirik** [comment]
@ehildenb 
The only comment unaddressed is the disequality predicate for integers. However, that is an optimization issue, not a correctness issue. If you don't care about that, go ahead and merge.

Also, as far as repo management is concerned, do whatever you think is best. I don't have a strong opinion one way or the other; the important thing to me is that all expectations are clearly communicated.

**Review by sskeirik — APPROVED** [review]

**Comment by sskeirik** [comment]
@ehildenb 
Also, I just realized now that I am supposed to submit a review using the review button. That wasn't clear to me as this was my first time doing a github review. If you bring anyone else on board to do this, it would be good to let them know if they haven't done this before.

**Pull request merged**
