### PR TITLE
Modularize the foform data-structures used by var-sat

### PR DESCRIPTION
**Pull request by ehildenb**
@nishantjr and @skeirik2 I've made it so that var-sat only depends on the QF fragment of the foform file (splitting modules into two when needed in foform).

I think we can do a similar thing we've been doing by stubbing out the `QF` prefixed modules with ones from EQFORM (which is already instantiated to `Term`, which is what foform.md assumes).

I'm doing a big testing run now, will push up fixes as I find bugs.

### CODE REVIEW

**Comment by sskeirik** [comment]
@ehildenb Thanks for doing this. I will play around with it when I am done with my current task.

**Comment by ehildenb** [comment]
@skeirik2 if you think you could look at this PR and fix the remaining broken tests, that would be great (it's somewhat hard for me to know exactly what/where/how to fix it).

Running `./build test tests/tools/varsat/var-sat` will show the broken test/output. Some of them are switched from `true` to `false`, and a couple tests are added.

If you do `git show` on the last commit, you'll see the final step which switches to depending on EQFORM from FOFORM (everything above is just refactorings of FOFORM to look more like EQFORM).

**Comment by sskeirik** [comment]
@ehildenb I'll take a look soon. Thanks for letting me know.

**Comment by ehildenb** [comment]
@skeirik2 I've updated this branch again, please look at commits f351738 and 2457a72 which add some tests/functionality before migrating to the new data-structures and check that the changed test-output makes sense.

**Comment by ehildenb** [comment]
Closing as I've found multiple bugs in the var-sat code which should be addressed and tested before refactoring it.

**Pull request closed without merging**
