### PR TITLE
build: make filenames safe for windows

### PR DESCRIPTION
**Pull request by sskeirik**
For reference, the forbidden characters include:

< (less than)
> (greater than)
: (colon - sometimes works, but is actually NTFS Alternate Data Streams)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)

This is in preparation for a proper native Windows build of Maude which will make managing future courses easier.

### CODE REVIEW

**Comment by ehildenb** [comment]
@skeirik2 can you try building on windows and see if there are any other easy fixes to include in this PR?

**Comment by sskeirik** [comment]
@ehildenb I have finally successfully built a _static_ Windows executable!

Unsurprisingly, many things do not work in this version, including:
- erewrite (depends on sockets/poll which use different APIs on Windows)
- most signal handlers
- all timer stuff (timing how long it took to evaluate a rewrite sequence)
- some parts of the terminal UI
  - currently the prompt does not display correctly (a bug I introduced when stripping things out)
  - ANSI escape sequences for color are not supported (but there is a low-level windows function which can enable this, starting in Windows 10)

As far as I am concerned:
- erewrite support for Windows is the lowest priority item (very few people will ever use it)
- signal handler support is probably a nice-to-have, since I assume it is only called in exceptional cases so that errors can be reported more nicely --- but I think I could sleep soundly if errors were ugly
- getting the timer to work right is important
- getting the console prompt to display properly is important
- ANSI escape sequences should be supportable without much work, but if that proves to be incorrect, they are not worth keeping

Aside from the above, what is left to do is write some proper `#ifdef`s so that the Windows bit only get built when needed.

EDIT: I haven't even touched the SMT rewriting stuff, which is a whole different can of worms. My desire to work on that currently is low---especially given the target users are essentially students who don't want to mess around with complicated installation processes.

EDIT: For the sake of completeness, the CVC4 build instructions mention that compiling for MinGW is possible --- this means that --- in theory, it wouldn't be hard to build it --- assuming that all of the dependencies it has were also built...

EDIT: Also, documenting the build process somewhat so that it is ...slightly... easier for the uninitiated would be good.

**Comment by ehildenb** [comment]
Hmmm, this is good documentation of the issues with building on Windows. I don't think we can merge this as-is though, because it breaks existing builds.

Perhaps though we could draw Steven Eker's attention to this and he may be able to make Alpha120 able to build on Windows.

**Comment by sskeirik** [comment]
Right, I completely agree. A pending task is put things behind appropriate `#ifdef`s, so that the build works in whatever environment you are on. I have been committing things in their current state as a way of documenting my work, just as you indicated.

**Pull request closed without merging**
