### PR TITLE
Include `eqform`, a simpler `foform`

### PR DESCRIPTION
**Pull request by ehildenb**
This is @skeirik2 's code. @skeirik2 if you have any test cases (even just really basic sanity checks), can you push them to this branch?

It would be nice to refactor `foform` to reuse this structure, if possible, to reduce code bloat, but I think it should be fine to do that in a later PR.

### CODE REVIEW

**Comment by ehildenb** [comment]
@skeirik2 the place to add tests is `tests/tools/meta/eqform.maude`.

**Comment by sskeirik** [comment]
I found a bug last night and just pushed up a fix. I will create a few basic tests later today or tomorrow and push those up.

**Comment by ehildenb** [comment]
@skeirik2 awesome, thanks. Can you look at `git log` (or `git hist` if you have it: https://github.com/ehildenb/dotfiles/blob/08a5bafaac1f060da62913d57b8ad08eb01828a8/git/gitconfig#L48) for the convention we've been using for commit messages? Basically we prefix the message with the affected files/directories to make it easier to see what parts of the source affects.

**Comment by ehildenb** [comment]
@skeirik2 I've fixed the commit messages, as well as a bug I had introduced where we were tracking the generated `maude` file in the repo.

When you get a chance, add some simple tests (esp one for the issue you found with `nnf` would be good).

**Comment by nishantjr** [comment]
Looks good!

I've pushed a couple of minor typo fixes and a change to the documentation that I think makes things more readable.

Is the eventual plan to have `FOFORM` include and reuse this?

* The set union operator `(_|_)`  is easily confused with the constructor for constrained terms. This may be a good time to think of renaming one or the other?
* I'm curious about why `EQFORM-IMPL` is parameterized?
* By tree like traversal, you mean traversing over the structure of the formula? Since the axioms of `/\` and `\/` both ACU how is this different from using a set (assuming tree like traversal is feasible)?

**Review by nishantjr — APPROVED** [review]

**Comment by ehildenb** [comment]
Yes, `foform` should eventually be refactored to use these data-structures instead. `EQFORM-IMPL` is parametric so that we can instantiate it over concrete syntax and use it directly in our system descriptions.

I agree that the operator is confusing, but I think we will be doing a major operator naming overhaul for all lists/sets once we have better infrastructure for generating them.

**Pull request merged**
