### PR TITLE
Factor out common-use modules from monolithic libraries

### PR DESCRIPTION
**Pull request by ehildenb**

### CODE REVIEW

**Comment by ehildenb** [comment]
@skeirik2 this factors out `SUBSTITUTION-SET`, which I remember you saying that you said there were some extra operations over these data-structures that you used. Can you post which ones they were, and I'll make sure they're included?

**Comment by sskeirik** [comment]
From SUBSTITUTION-HANDLING, I want:
- substitution application (_<<_) to terms and substitutions
- substitution composition (_.._)
- substitution restriction to variables _|>*_
- dom_inVars_, dom_notInVars_
 
Actually looking again, I don't think I need anything in particular from SUBSTITUTIONSET, the main thing I want is the functorial lifting of _<<_ to SubstitutionSets/TermSets, i.e. _<<_ : TermSet SubstitutionSet -> TermSet, but that is something I wrote and not actually in FULL-MAUDE.

The other main dependencies I have:
- UNIT, but I have a version of UNIT in my varsat-update branch called UNIT-FM that is essentially extracts most of the (useful) features out of UNIT that can be used
- VariantTripleSets (I understand you pulled this out already)

Looking foward, the RL Tool has a bit more extensive dependency on FULL-MAUDE, but I think that the main thing I need is:
- eMetaPrettyPrint and friends (this is a big dependency and really should be its own library) --- it essentially parses Maude OpDecl Qid arguments, finds out where the blanks are, then pastes the arguments into the blank spaces recursively

A nice to have but not necessary feature is:
- Module evaluation (the bulk of FULL-MAUDE is solving this problem); however, I believe that metaInterpreter should pave the way for a dramatic simplification of the module evaluation code because it seems to be the case that one can pass pass a meta-module expression to the the metaInterpreter, let it evaluate it, and then obtain the evaluated meta-module out of the interpreter

**Comment by ehildenb** [comment]
@skeirik2 I've added `_<<_ : SubstitutionSet SubstitutionSet << SubstitutionSet`, but think I'll wait on adding the other operators until we have a system which uses (and thus tests) them which one of us is trying to add.

**Review by sskeirik — APPROVED** [review]
I like the .SortX syntax for identities for X data structure over Sort because it is a clear convention that generalizes to any number of data structures without ambiguity.

One issue to be aware of is a potential ambiguity between (...) .SortX to mean unioning/appending parenthesized term with .SortX and coercing parenthesized term to SortX. I'm not sure how the Maude Parser will treat the whitespace in that case.

Also, if rewrite numbers break the tests, they can be removed if you want:

`set show stats off`

**Pull request merged**
