### PR TITLE
Factor out `set show timings off .`

### PR DESCRIPTION
**Pull request by nishantjr**

### CODE REVIEW

**Comment by ehildenb** [comment]
Should we move all tests over to `maude-test-wrapper`?

**Comment by nishantjr** [comment]
Looks like only `smtTest` is the only one left? That one needs it so it can run conditionally depending on whether CVC4 / Yices are compiled in. Later in the NO branch, I've added some infrastructure for removing the duplication there too.

**Comment by nishantjr** [comment]
Maybe I should bring that onto this branch. I'd like to be running CI with both CVC4 and Yices (some of the NO tests only go through on one of them), but right now we can't have a build with both of them and would have to do two different builds.

**Comment by ehildenb** [comment]
Ah I see, a previous commit went through and removed all the `sh` files, which is why this one only removes one for `var-sat`. Ok, sounds good, feel free to merge.

**Pull request merged**
