### PR TITLE
Add views to `EQFORM` from FVP data-structures

### PR DESCRIPTION
**Pull request by ehildenb**
@skeirik2 here is an example of using the parameterized `EQFORM` for some other data-structures.

It's nice because then we can use the `EQFORM` directly in definitions at the object level, and not just for manipulating terms, but also for manipulating terms, and know that they have the same semantics (since they stem from the same parameterized module).

Still cannot solve the issue of wanting proper subsorting propagated through the parameterized module, but that's a problem for another day.

### CODE REVIEW

**Review by sskeirik — COMMENTED** [review]
By the formula transformations, we still get the effect of evaluating ~/tt/ff (which were previously evaluated by computing variants), so that's good.

My concern is that, for testing var-sat code, having equality/disequality predicates for Nats/Ints is important. The _==_ and _=/=_ operators for Nat and Int can still be defined directly without using Boolean negation which would let you keep those operators in your current formulation. Do you have other plans to deal with that? Otherwise, this will break all of the var-sat tests basically.

**Comment by ehildenb** [comment]
Well the `var-sat` tests pass currently, are there more tests you have locally which should be added in another PR?

The reason for avoiding defining `==` and `=/=` for `Nat` is because we wanted to directly use the Maude versions of them over sort `Bool`. This makes us able to directly write concrete syntax in the side-conditions of rules, though the semantics are incorrect. So we still transform the theory to one where the `_?=_` is used instead of `_==_`, and `_!=_` instead of `_=/=_` before doing any narrowing.

**Comment by sskeirik** [comment]
@ehildenb I am totally lost. I did forget earlier that github runs integration tests but my local builds on both master and this branch are failing --- and that is after './build clean' and a ./build maude' and then going to the test folder to run the tests in the /tests/meta/ and /tests/tools/fvp and /tests/tools/varsat. Do your local builds are pass?

**Comment by ehildenb** [comment]
You also must do `./build tangle` (and before that, `./build deps`). If you've already `./build tangle` a single time, you may need to manually `cd contrib ; make -B` (*after* doing `./build deps`).

**Review by sskeirik — APPROVED** [review]
I trust that my build process is broken here and works other places.

**Pull request merged**
