### PR TITLE
contrib/systems/bitswap: CS 476 project

### PR DESCRIPTION
**Pull request by nishantjr**

### CODE REVIEW

**Comment by nishantjr** [comment]
Still need to write the test driver `tests/systems/bitswap` and expected files

**Comment by ehildenb** [comment]
@nishantjr is it absolutely necessary to use `panpipe` here? If so, can we add a submodule dependency?

**Comment by nishantjr** [comment]
Panpipe isn't necessary only for building the paper (the tangled code and tests are executable without it). It would take a 10s of lines to implement something equivalent in Lua and stick it in the tangle repo, which I think is the right way to go.

**Review by ehildenb — APPROVED** [review]
Looks good!

**Pull request merged**
