### PR TITLE
Add simple check to test whether generated maude files load

### PR DESCRIPTION
**Pull request by ehildenb**
This can be used as a much quicker CI/sanity functionality when testing many commits.

### CODE REVIEW

**Comment by nishantjr** [comment]
This is testing that the file load without warnings, and without needing additional `loads` (since tests in `tests/` often manually load other stuff, they may hide missing dependencies). Is that correct? 

```
{   cat "$test_name"
    echo "quit"
} | $maude_exec -no-banner -no-advise &> "$tmp_output"
```
can probably become :

```
cat "$test_name" | $maude_exec -no-banner -no-advise </dev/null &> "$tmp_output"
```
It terminates better too, if there is a syntax error in the test file ("quit" would have it stay open waiting for input I think).

**Comment by ehildenb** [comment]
This doesn't make sense to me, seems like you're providing two standard inputs to `$maude_exec`. Indeed, running `make test-load` in the `contrib/` directory runs very fast, because it's not actually loading the files (I checked by manually breaking one). The original version did catch the manual break.

**Comment by nishantjr** [comment]
Ah, you're right. I don't think you don't need either `quit` or `< /dev/null` then.  maude will quit when stdin closes

**Review by nishantjr — APPROVED** [review]
Looks good to me

**Pull request merged**
